### PR TITLE
fix: stack the all-day and time schedule from the top (fix #29)

### LINKED ISSUE #29: A schedule isn't shown at specific day
## Version

v0.6.6
v0.8.0 too.

## Development Environment

Mac, High Sierra
Chrome . :65.0.3325.162

## Current Behavior
Some schedule is not shown under specific condition in monthly view
That schedule is on 2018.03.09 in sample code.

image

```js
var cal = new Calendar(xxxxx, {
    ....
    month: {
        visibleScheduleCount: 3
    },
    ....
});

cal.setCalendarColor('SCHEDULE', {
    color: '#6d6d6d',
    bgColor: '#fef1f1',
    render: false
});
cal.setCalendarColor('IAMSCHOOL', {
    color: '#6d6d6d',
    bgColor: '#ebf2ff',
    render: false
});

cal.createSchedules([
    {
        id: '10',
        calendarId: 'SCHEDULE',
        title: '1',
        category: 'time',
        dueDateClass: '',
        start: '2018-03-09T09:00:00+09:00',
        end: '2018-03-09T10:00:00+09:00',
        isReadOnly: true
    },
    {
        id: '1',
        calendarId: 'IAMSCHOOL',
        title: '2',
        category: 'allday',
        dueDateClass: '',
        start: '2018-03-06T09:00:00+09:00',
        end: '2018-03-08T09:00:00+09:00',
        isReadOnly: true
    },
    {
        id: '2',
        calendarId: 'IAMSCHOOL',
        title: '3',
        category: 'allday',
        dueDateClass: '',
        start: '2018-03-07T09:00:00+09:00',
        end: '2018-03-09T09:00:00+09:00',
        isReadOnly: true
    },
    {
        id: '3',
        calendarId: 'SCHEDULE',
        title: '4',
        category: 'allday',
        dueDateClass: '',
        start: '2018-03-06T09:00:00+09:00',
        end: '2018-03-08T09:00:00+09:00',
        isReadOnly: true
    },
    {
        id: '4',
        calendarId: 'SCHEDULE',
        title: '5',
        category: 'allday',
        dueDateClass: '',
        start: '2018-03-06T09:00:00+09:00',
        end: '2018-03-08T09:00:00+09:00',
        isReadOnly: true
    },
]);

cal.render();
```

## Expected Behavior

The schedule on 2018.03.09 should be shown.

### PR DESCRIPTION
**Pull request by dongsik-yoo**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

#### AS-IS
The time schedule had a top index bigger than all-day schedule. Any empty position was not used between all-day schedules.

#### TO-BE
The time schedule has a top index at empty position from the top.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/controller/viewMixin/month.js [hunk 1]
```diff
@@ -134,16 +174,18 @@ var Month = {
      * @param {Date} start - start date to find schedules
      * @param {Date} end - end date to find schedules
      * @param {function[]} [andFilters] - optional filters to applying search query
+     * @param {boolean} [alldayFirstMode=true] if true, time schedule is lower than all-day schedule. Or stack schedules from the top.
```
Comment (youjung-hong) [inline src/js/controller/viewMixin/month.js]: `alldayFirstMode = alldayFirstMode || false` => `alldayFirstMode=false`?
